### ISSUE TITLE
Some properties undocumented

### ISSUE THREAD

**Issue by macMikey** [4d-for-ios/4D-Mobile-App-Server#1]
In the [docs for push notifications](https://github.com/4d-for-ios/4D-Mobile-App-Server/blob/18R4/Documentation/Classes/PushNotification.md), I see several parameters/properties that are implemented but undocumented:
*badge*
*sound*
*mutable-content*
*category*
*url*
*data*

Is there a reason for that, or can I work on adding them?

**Comment by mesopelagique** [comment]
No particular reason, only maybe that it will not be compatible with android and we could change some property names (but keep compatibility)
_and when developing it, it was not asked by my "project owner" so it was just optional_

we could edit the doc and add it yes
I will close the issue when its done

**Comment by mesopelagique** [comment]
Hi I added a new chapter in doc here in master branch

https://github.com/4d-for-ios/4D-Mobile-App-Server/blob/master/Documentation/Classes/PushNotification.md#additional-properties

(and see that 19.X branch has not been yet pushed, so I push it on github, i will report the doc maybe)
